---
title: "2-Deoxy-D-glucose 通过非编码RNA MEG3抑制髓母细胞瘤的生长"
format: docx
bibliography: medulloblastoma_reference.bib
csl: "/home/yincy/git/github/styles/chinese-gb7714-2005-numeric.csl"
editor: source
number-sections: true
---

# 摘要{.unnumbered}
髓母细胞瘤（Medulloblastoma，MB）是一种非常恶性的中枢神经系统肿瘤，主要发生在儿童和青少年时期，其造成的死亡率大约为30%。因此，迫切地需要找到一种治疗MB的方案。鉴于肿瘤细胞需要维持一个非常高的代谢速率去支撑其旺盛的分裂速度。因此，本研究旨在研究阻断MB的能量代谢途径后如何影响其分裂与生长。2-Deoxy-D-glucose（2DG）属于葡萄糖类似物，由于其缺失2号位上的氧原子，因此不能被HK2磷酸化，进而抑制了糖酵解过程。因而，2DG被认为是一个潜在的治疗肿瘤的化合物，但是其对MB的影响目前还不清楚。在本研究中我们发现2DG在体内和体外都能够有效地抑制MB的生长与分裂。此外，通过二代测序发现2DG调控MB生长与分裂是部分地通过调控非编码RNA MEG3和MYRIP实现的。后续的研究证实在MB细胞系中MEG3下游信号同样受到2DG的调控。因此，本研究发现了一个2DG调控MB生长与分裂的信号通路，该通路可以作为潜在的治疗MB的靶点。

**关键词：**髓母细胞瘤；2-脱氧-D-葡萄糖；lncRNA MEG3；肿瘤治疗

# Abstract{.unnumbered}
Medulloblastoma (MB), a highly malignant tumor commonly found in youngsters, unfortunately, results in a mortality rate of around thirty percent. Consequently, there is a critical need to enhance the prognosis of MB by formulating novel treatment strategies. Given that cancer cells demand a substantial energy supply to sustain their high proliferative rate, our approach aims to target and block this energy supply, thereby impeding cancer cell growth. 2-Deoxy-D-glucose (2-DG) is a glucose analog that lacks the oxygen atom at position 2, rendering it unable to be phosphorylated by HK2 and inhibiting glycolysis. While 2-DG has been considered a potential therapy for cancer treatment, its role in MB hasn’t been fully elucidated. In our current study, we discovered that 2-DG inhibits the progression of MB in both in vitro and orthotopic transplantation tumor models. Furthermore, analysis of the orthotopic transplantation tumors from the 2-DG treatment and control groups revealed significant up-regulation of lncRNA MEG3 and MYRIP in the 2-DG treatment group. We further demonstrated that the downstream factors of MEG3 are also regulated by 2-DG in the MB cell line. In conclusion, our results revealed that 2-DG inhibits the progression of MB and suggested a novel mechanism for its treatment. This provides evidence that 2-DG could be a potential therapeutic strategy for treating MB.

**Keywords:**Medulloblastoma; 2-Deoxy-D-glucose; lncRNA MEG3; Cancer treatment


# 前言
## 背景
髓母细胞瘤（Medulloblastoma，MB）是一种恶性的中枢神经系统肿瘤，起源于小脑的髓母细胞瘤。髓母细胞瘤是儿童和青少年最常见的原发性恶性脑肿瘤之一，但也可在成年人中发生。目前的统计显示其有两个发病高峰期，分别为1-4岁和5-9岁，约占儿童神经系统肿瘤的15-20%[@Massimino2016-ls;@Distel2003-zo]。在成年人中的发病率约为每百万人中有0.5个病例，且男性的发病率明显高于女性，比率约为1.8：1。在儿童和青少年中的发病率约为每年每百万人口中有5至6例[@Northcott2019-ah;@Ostrom2018-kv]。这意味着全球每年大约有1,500至1,800例新发的髓母细胞瘤病例。尽管对于髓母细胞瘤的流行病学研究不是很多，但是目前显示不同地区和不同种族中髓母细胞瘤的发病率没有明显的差别。根据中国的流行病学数据，髓母细胞瘤在中国儿童和青少年中的发病率约为每年每百万人口中有3.2至4.7例。在欧洲的统计显示儿童MB患者1年、3年和5年的生存率分别为81%、63%和56%。婴儿相应的生存率要低一些，而5-14岁的青少年的生存率则要高一些[@Massimino2016-ls]。髓母细胞瘤通常位于小脑后下方的中线位置，可以对周围的组织和脑脊液产生压迫和侵袭。它的发展速度较快，可能会扩散到脊髓和其他脑部结构。髓母细胞瘤的症状通常包括头痛、呕吐、平衡障碍、共济失调、步态异常、眼球运动异常、视力问题以及其他神经系统症状。

目前除遗传和出生体重两个因素是已经证明与髓母细胞瘤的发生有关联外，而饮食、环境等因素在髓母细胞瘤发生中的作用还不清楚[@Northcott2019-mg]。如痣样基底细胞癌综合征（Gorlin syndrome）、家族性腺瘤性息肉病（FAP syndrome）、布朗姆综合征（Bloom syndrome）和Nijmegen断裂综合征（Nijmegen breakage syndrome）等都会增加罹患髓母细胞瘤的风险[@Taylor2002-id;@Cohen1982-rc;@Petrella1991-ma;@Distel2003-zo]。而Harder等人的研究发现出生体重与MB的发病有着明显正相关关系[@Harder2008-nq]。基于1022个MB样本的研究发现大约5.9%的MB患者会发生APC、BRCA2、PALB2、PTCH1、SUFU和TP53突变，但是这些突变在临床上并没有产生易患MB的综合征，因此这些突变在MB发生发展过程中的作用还有待进一步的研究[@Waszak2018-df;@Northcott2019-mg]。此外，有一项在英格兰的研究发现在怀孕期间母体受到病毒感染则会使患神经系统肿瘤的风险增加11倍之多[@Fear2001-kk]。另外一个统计学的研究发现在婴儿早期没有社交会使其MB的发生率提高约1.78倍（95%CI: 1.12-2.83）[@Harding2009-ks]。

## 髓母细胞瘤的分类
2007年世界卫生组织根据形态学将髓母细胞瘤分为一下5个亚群desmoplastic/nodular-MB、MB-with extensive nodularity（MBEN）、anaplastic-MB、large cell-MB、以及将不符合上述特征的归类为classic-MB[@Louis2007-jc]。classic-MB由一群细胞核呈圆形到椭圆形或者胡萝卜形状的致密细胞组成，这些细胞的染色质颜色较深，细胞核周围的细胞质较少。Desmoplatic/nodular-MB是一个形态多样的MB亚群，主要表现为核质比小于正常细胞、组织呈纤维状、细胞形态类似于神经细胞等。。MBEN主要出现在婴幼儿期，通常伴随着较好的预后。large cell-MB具有较大呈圆形且多囊泡的细胞核，核仁比较多[@Massimino2016-ls]。随着测序技术的普及，全球多个组织的研究发现在转录组水平上可以将髓母细胞瘤分为以下四个亚类：WNT-MB，SHH-MB，Group3-MB和Group4-MB[@Taylor2012-ab]。

WNT-MB是最不常见的MB，约占所以MB的10%，在男性和女性中发病的概率大致相当，在所有年龄段都能够发生，但是高发期在10-12岁[@Kool2012-kt]。WNT-MB的一个特征是其发病周期相对于其他MB亚型非常长，因此，大部分WNT-MB患者都是死与其他疾病而非WNT-MB。在确诊时WNT-MB基本上没有发生转移，如果确诊时年龄小于16周岁，5年生存率超过95%，但是如果在成年期确诊，则5年生存率要小一些[@Remke2011-en;@Clifford2015-pi]。约85%-90%的WNT-MB患者的CTNNB1基因（编码β-catenin）在第三个外显子处发生突变，导致β-catenin不能被有效降解，致使其在细胞核内不断累积，这导致WNT信号通路的异常激活。WNT-MB的另外一个特征是大约80-85%的患者的MB细胞只有一条6号染色体，而且6号染色体缺失通常与CTNNB1同时出现。除此之外，WNT-MB细胞的基因组相对比较稳定，没有明显的大片段缺失和重复[@Northcott2012-wl]。此外，WNT-MB基因组有着比较高的单核苷酸突变（single-nucleotide variants, SNVs），平均每1800个核酸就有一个突变。最新的研究显示在WNT-MB中最常见的基因突变为DDX3X（36%）、SMARCA4（19%）、TP53（14%）、CSNK2B（14%）、PIK3CA（11%）和EPHA7（8%）[@Northcott2017-ou;@Jones2012-jg;@Pugh2012-zg;@Robinson2012-tk]。DDX3X突变可能是通过促进rhombic lip 祖细胞（rhombic lip progenitor）分裂来促使WNT-MB发生的，因为rhombic lip祖细胞被认为是WNT-MB的主要来源[@Robinson2012-ra;@Gibson2010-gu]。SMARCA4编码SWI-SNF染色质重塑复合物的一个亚基，而改复合物能够通过改变染色质的局部结构来调控基因的转录。据估计SWI-SNF复合物在大概20%人类肿瘤中发生了突变。SMARCA4基因和SWI-SNF复合物中的另外两个组分ARID1A和ARID1A2在WNT-MB中有如此高的突变率说明调控SWI-SNF介导的染色质结构调控在WNT-MB的发生和发展过成中起到了非常重要的作用。CSNK2B编码CKII（casein kinase II）的β亚基。CKII能够调控多个信号通路，如代谢通路、信号传导通路、转录以及细胞复制等信号通路。此外，CKII还能够通过磷酸化CTNNB1激活WNT信号通过，促进TCF-LEF家族基因的表达，从而促进细胞分裂[@Dominguez2009-pm;@Duncan2008-df]。PIK3CA是一个致癌基因在许多肿瘤都发生突变。其主要通过持续地激活AKT和mTOR通路来促进续细胞非正常的生长和分裂[@Vanhaesebroeck2012-py]。EPHA7编码的蛋白属于ephrin家族的络氨酸激酶家族受体，其在中枢神经系统发育过程中高表达，主要介导神经细胞的空间分布、轴突生长以及突出的产生等过程[@Saha2018-np]。但是这些突变在WNT-MB产生过程中的具体作用还有待继续探究。WNT-MB患者由于高表达WIFI和DKK1导致肿瘤附近的血脑屏障（blood-brain barrier， BBB）功能受到损坏，恰巧的是WIFI和DKK1是WNT信号通路的拮抗剂，这可能可以部分地解释为什么WNT-MB患者有着较好的预后。此外，由于WNT-MB患者血脑屏障的功能受到损坏，可以利用该现象从外周给患者使用化疗药物。

SHH信号通路在小脑中通过促进神经干细胞和其他组织细胞的分裂在小脑的发育过程中起到了非常重要的作用。Purkinje细胞分泌的SHH信号通路的配体通过作用于颗粒细胞的祖细胞（granule cell precursor，GCP）促进external germinal layer（EGL）的形成[@McManamy2007-zk]。来自SHH通路的旁分泌信号或者由于突变导致PTCH1持续激活会使G蛋白偶联受体SMO与PTCH1分离，分离后SMO会转移到初级鞭毛的顶端（tip of the primary cilium）致使GLI2从其受体上释放出来。GLI2随后转移到细胞核促进许多与细胞增殖相关基因的表达，因此促进MB的发生[@Archer2012-ct]。。SHH-MB是目前了解最多的MB亚型，绝大多数SHH-MB患者都有SHH信号通路关键基因的突变和拷贝数的变化。SHH-MB主要依赖转录组去诊断，其他的诊断方法主要通过组化染SFRP1或者GAB1[@Cho2011-ry;@Kool2008-cr;@Schwalbe2011-nc]。这些突变包括PTHC1（43%）、SUFU（10%）、SMO（9%）、GLI1或者GLI2（9%）以及MYCN（7%）。这些基因的突变导致SHH信号通路非配体依赖的，持续性地激活，这导致SHH响应基因的高表达，从而促进细胞的增值和分裂。此外，在小鼠身上的研究还证实突变这些基因会导致SHH-MB的形成[@Markant2012-cs;@Lau2012-uo;@Wu2011-ur]，说明这些基因在SHH-MB行程过程中起这重要的作用。最近的研究还发现p53和PI3K信号通路同样也在SHH-MB中起着重要的作用[@Clifford2006-tz]。SHH-MB染色体有一个特征是第九号和第十号染色体的长臂丢失，这导致位于其中的抑癌基因PTCH1和SUFU的丢失，且其编码的蛋白可以抑制SHH信号通路[@Northcott2010-io]。在大概39%的SHH-MB的病人中发现TERT（影响端粒的长度）启动子（TERT promotor mutations）区域发生突变，而在非SHH-MB亚型中只有不到5%的突变率。此外，98%成年SSH-MB患者的体细胞具有TERT突变（somatic mutation），而在婴儿和儿童中的突变率分别只有13%和21%[@Jakacki2012-ey]，但是这种年龄依赖的TERT启动子区域的突变的意义是什么目前还不清楚。相较于WNT-MB，SHH-MB亚型的表型无论是从染色体结构变异的角度还是从生存率的角度来说都都具有比较大的差异[@Kool2014-go;@Cavalli2017-ko;@Northcott2011-wc]。近期，多个研究小组利用基因表达数据和DNA甲基化数据将SHH-MB又划分成了4个亚群（SHHa、SHHβ、SHHγ和SHHδ）[@Cavalli2017-ko]。同样利用DNA甲基化和基因表达数据，另外一项研究儿童MB分为iSHH-I和iSHH-II两个亚群。iSHH-I多发生在年龄较小婴儿期，同时SUFU发生突变和2号染色体多拷贝。iSHH-II主要特征为SMO激活突变、以及染色体修饰基因KMT2D和BCOR的突变[@Robinson2018-uf]。这些分子层面的特征显示iSHH-I和iSHH-II分别类似于SHHβ和SHHγ。在年龄稍大一些的儿童和青少年SHH-MB患者中TP53基因的突变率要明显高于婴儿和儿童SHH-MB患者，同时TP53的突变还伴随着MYCN或者GLI2的高表达、细胞变大和组织增生以及染色体断裂性重组（chromothripsis）[@Rausch2012-vg]。相较于具有TP53突变的WNT-MB，具有TP53突变的SHH-MB患者通常具有较低的生存率，这可能是由于TP53在不同细胞中突变产生的影响不同导致的[@Zhukova2013-ba;@Ramaswamy2016-wx]。相较于儿童及青少年SHH-MB患者，成年SHH-MB患者通常具有较高的SNVs，同时超过80%的患者还伴有PTCH1和SMO突变[@Kool2014-vw]。由于SMO位于SHH信号通路的上游，靶向SMO的临床治疗表现出较好的治疗效果[@Petrirena2018-xn;@Lou2016-vl;@Robinson2015-mw;@Gajjar2013-vd]。

Group3-MB约占所有MB的25-28%，而且基本上只发生在儿童期，并且男性要多余女性。Group3-MB属于恶性肿瘤在发现时基本上都已经发生了转移[@Northcott2012-wv]。高表达MYC是Group3-MB的一个重要特征，在其他MB亚型中几乎没有观察到MYC的表达升高[@Northcott2017-ou;@Northcott2012-rq]。使用转录组和蛋白质组的的数据发现Group3-MB同时还伴随着核糖体蛋白、核糖体组装蛋白、线粒体中的核糖体蛋白、以及与mRNA修饰、转录和转运的蛋白都在Group3-MB中高表达[@Archer2018-pp;@Forget2018-wu]。Group3-MB中常见的共有突变比较少，突变率大于5%的目前只发现了SMARCA4（9%）、KBTBD4（6%）、CTDNEP1（5%）和KMT2D（5%）[@Northcott2017-ou]。KBTBD4属于Kelch-BTB-BACK家族，目前对其功能了解的还比较有限，其可能在泛素-蛋白酶系统中发挥这某种功能。KBTBD4突变通常发生在Kelch功能区，可能会影响其与其他蛋白或者底物得结合。CTDNEP1属于蛋白磷酸酯酶（protein phosphatases），能够将其底物去磷酸化，其可能通过正向调控WNT信号通路参与生殖细胞的形成[@Tanaka2013-ha]。但是目前对于CTDNEP1在Group3-MB中所起的作用了解还非常的欠缺。其他在分子层面促进Group3-MB形成的因素还包括MYCN（5%）和OTX2（3%）的高表达。OTX2是一个转录调控因子，在前脑、后脑、眼睛和松果体的发育过程中起到非常重要的作用[@Beby2013-qv;@Simeone1998-sw]。目前认为OTX2基因的高表达对于维持MB细胞的干性、抑制神经细胞分化和调控细胞周期等方面发挥着重要的功能[@Boulay2017-ka;@Garancher2018-vw;@Bunt2012-xy;@Bunt2013-la]。染色体结构变异导致GFI1和GFI1B在大约15%-20%的Group3-MB患者中表达升高[@Northcott2014-eg]。GFI1和GFI1B在造血系统中高表达可以抑制造血干细胞的分化。将过表达MYC同时过表达GFI1或者GFI1B的小鼠神经干细胞接种到免疫缺陷小鼠的后脑能够促使前者向Group3-MB表型分化[@Northcott2014-eg]。在染色体层面上，Group3-MB表现出明显的非整倍性（aneuploidy），同时伴随17号染色体表现出等臂染色体（isochromosome）现象（即17号染色体由两个长臂构成，短臂丢失）、1号染色体长臂和7号染色体多拷贝、8号染色体和10号染色体长臂以及16号染色体长臂丢失等现象[@Northcott2012-wl]。通过使用不同的组学技术，近期的研究又将Group3-MB进行了更细致的划分[@Cho2011-zi;@Northcott2017-ou;@Cavalli2017-ko;@Schwalbe2017-au]。如有一项研究把Group3-MB分为两个小类，分别称为c1和c5。c1亚群表现为MYC高拷贝和高表达，同时病情较差。而c5表现为染色体非整倍性以及较好的病情。其他的研究也有将Group3-MB划分成两歌亚类或者三个亚类的，但是所有的亚型只要MYC高拷贝或者高表达，患者的病情通常较差[@Cavalli2017-ko;@Schwalbe2017-au]。

Group4-MB是最常见的MB亚型，超过30%的MB患者都属于Group4-MB，除了婴儿期在所有年龄段都可以发生。而且Group4-MB在男性中的发病率约为女性的2-3倍[@Taylor2012-ab;@Massimino2016-ls]。与Group3-MB类似Group4-MB亚群中并没有发现常见的共有突变，Group4-MB的诊断类似于Group3-MB，主要通过计算其转录组于其他Group4-MB样本的相似性进行诊断[@Taylor2012-ab]。在Group4中最常见的一个现象是由于enhancer-hijacking导致的PRDM6的高表达（17%）[@Northcott2017-ou]。在Group4-MB PRDM6高表达患者中常常发现位于PRDM6启动子上游约500kb的SNCAIP出现串联重复，说明这个结构变异对于PRDM6的持续高表达可能起着某种作用[@Northcott2017-ou;@Northcott2012-rq]。PRDM6是一个染色质修饰基因，目前已知其在内皮细胞和血管平滑肌细胞祖细胞中能够抑制基因的表达，但是PRDM6的异常表达在Group4-MB中所起到的作用目前还不清楚[@Wu2008-jw;@Davis2006-hq]。Group4-MB中的其他常见突变基本上都与组蛋白修饰有关，如KDA6A（9%）、ZMYM3（）、KMT2C（6%）以及KBTBD4等。此外，还有一些基因表达升高，如MYCN（6%）、OTX2（6%）、CDK6（6%）等。以及enhancer-hijacking导致的GFI1或者GFI1B的高表达（5%-10%）。KDM6A、ZMYM3和KMT2C编码的都是染色质修饰蛋白，其功能失活性突变在Group4-MB中基本上都是单独出现[@Northcott2017-ou]，并且在非Group4-MB中极少发生，说明它们影响的下游信号可能是相同的。CDK6属于细胞周期调控激酶，其与CDk4共同调控细胞穿过G1-S周期，在Group4-MB动物模型上使用CDK4/CDK6抑制剂显示出良好的临床效果[@Cook_Sangar2017-yv;@Sherr2016-sp;@Cook_Sangar2017-eg]。染色体大面积异常在Group4-MB中非常常见，特别是7号染色体多拷贝（40%-50%）、17号染色体长臂多拷贝（>80%）、8号染色体（40%-50%）和11号染色体（>30%）以及17号染色体长臂（>75%）缺失[@Northcott2012-wl]。与Group3-MB类似17号等臂染色体在Group4-MB中也非常常见。此外在Group4-MB女性患者中缺失一个X染色体同样也非常常见（~80%）[@Taylor2012-ab]。近期有研究显示ERBB4-SRC信号通路在Group4-MB的形成过程中可能起到了一定的作用，但是其临床价值还有待进一步的验证[@Forget2018-er]。随着人们获得的关于Group4-MB的数据越来越多，将Group4-MB进行更为细致的划分也随之提了出来。有的研究将Group4-MB再细分为2个亚群，有的研究将其分为3个亚群。这些亚群具有不同的染色体结构和统计学特征，低风险组常伴随11号染色体丢失或者17号染色体多拷贝，而高风险组在确诊时通常都发生了转移[@Cavalli2017-ko;@Schwalbe2017-au;@Shih2014-uc]。

以上两种分类方法在划分MB亚类时存在一定的交叉，但更多体现的是不同。如desmoplastic/nodular-MB，以及几乎所有的MBEN在转录组水平上都属于SHH-MB亚类，classic-MB在分子层面上可以划分到WNT-MB、SHH-MB、Group3-MB和Group4-M，large cell-MB和anaplastic-MB在分子层面上也可以划分到WNT-MB、SHH-MB、Group3-MB和Group4-MB中，但是主要属于Group3-MB[@Ellison2011-yh;@McManamy2007-ba;@Northcott2011-pr]。

## 研究髓母细胞瘤的模型
随着近期对MB的了解越来越深入，人们开始意识到无论在临床上还是在分子层面上MB都具有非常大的差异。因此，无论是临床前研究还是临床实验都需要具体到MB的某个亚类。因而，构建不同的模拟MB亚类的动物模型就显得尤为重要。

CTNNB1在大约85-90%的患者中都发现带有突变，因此WNT-MB的动物模型主要是通过突变CTNNB1来构建的。目前有两个小鼠模型能够用于研究WNT-MB，第一个WNT-MB小鼠模型是在2010年由Gibson和其同事通过突变CTNNB1和敲除TTrp53构建出来的[@Gibson2010-gu]。由于只突变CTNNB1在小鼠身上是不能够诱导WNT-MB出现的，所以Gibson等人将Tp53敲除来促进WNT-MB的发生。但是在WNT-MB患者中CTNNB1和TP53同时突变的情况并不多见（<15%）[@Gibson2010-gu]。使用该小鼠Gibson等人发现WNT-MN起源于脑干的后侧而非小脑。而在WNT-MB患者的脑干区域都发现了WNT-MB肿瘤细胞[@Wefers2014-pk]。另外，Gibson等人还发现WNT-MB肿瘤组织中的血管都是有孔的（fenestrated），其能够使得化疗药物有效地进入肿瘤组织，提高化疗的效果[@Phoenix2016-ot]。在突变CTNNB1和Tp53的基础上Robinson等人再将Pik3ca突变掉，这使得构建出来的WNT-MB小鼠模型的发病率从不到15%提高到了近100%，而且发病时长从大约11-12个月缩短到只需要不到3个月[@Robinson2012-nk]。

目前用于研究SHH-MB的动物模型是最多的，且远超其他MB亚型。但是绝大多数的动物模型都是基于突变PTCH1和SMO基因。基于SMO突变的额动物模型发现SHH-MB来源于位于小脑和螺神经核（nucleus cochlearis）中的神经颗粒祖细胞（granule neuron precursors）[@Grammel2012-nd;@Schuller2008-vn]。PTCH1敲除小鼠在6个月内大约有15%-20%的小鼠会发展成SHH-MB，如果再敲除Trp53，则会使SHH-MB的发生率提高到100%，并且发病周期小于3个月[@Wetmore2001-dr]。另外还有过表达Mycn和敲除Sufu的SHH-MB小鼠模型[@Swartling2010-su;@Lee2007-ef]。此外，还有通过干预干扰素信号通路和DNA修复信号通路来模拟SHH-MB发生的[@Lin2004-kn;@Wang2003-qm;@Holcomb2006-is]。使用这些动物模型的研究发现SHH-MB起源于小脑颗粒状神经元祖细胞（cerebellar granule neuron progenitors，CNGPs）[@Yang2008-iw;@Schuller2008-zp]。

目前所有Group3-MB的动物模型都是通过过表达Myc或者Mycn来构建的，但是单独的过表达Myc或者Mycn并不足以促进Group3-MB的形成，通常还需要过表达抗凋亡基因，如Bcl-2等[@Jenkins2016-rv]。在多种神经干细胞或者神经祖细胞中过表达Myc所形成的MB在表型上类似于Group3-MB。通过过表达Gfi1或者Gfi1b诱导的MB具有很强的侵袭性，在表型和分子层面上都与Group3-MB类似[@Northcott2014-eg]。但是目前对于Group3-MB起源与小脑的哪种细胞还不清楚。

除了细胞系外目前没有用于研究Group4-MB的动物模型，其原因主要是目前人们对于Group4-MB形成的分子机制了解还非常的欠缺。此外，由于Group4-MB是所以MB亚群中占比最大的，其表型的多样化也是目前对其研究的主要障碍。还需要通过获得更多的组学数据对其更为详细的分类，以便后续对其分子机制的研究。

## 髓母细胞瘤的诊断方法
放射学手段可以用于检查后颅窝内的肿瘤，包括髓母细胞瘤（medulloblastoma，MB）、小脑星形细胞瘤（cerebellar astrocytoma）、上胚瘤（ependymoma）、脑干胶质瘤（brainstem glioma）、非典型类畸胎瘤/类横纹肌瘤（atypical teratoid/rhabdoid tumour）。因此，计算机断层扫描（CT）通常是诊断MB的第一选择。在CT图像中MB一个典型特征是中线、均质、造影剂增强的小脑蚓部肿块。核磁共振成像是手术前一项必须要做检查。MB典型的核磁共振图像特征包括T1加权成像上的异质低密度肿块。其他中枢神经系统的肿瘤在T2加权成像上表现为灰质高密度，而MB的T2加权成像介于灰质和白质之间，反映了较高的细胞密度。MB的对比增强是不均匀的，多大40%的患者会出现脊柱转移，并且常位于腰骶部和胸部。对于可疑病例，应通过轴向切片进行确诊或者排除，因此，在开始任何辅助治疗前必须进行脊柱MRI检查。T2薄片可以用于观察无强化的脑膜扩散中的小结节，而T1加造影序列可能对其估计不足。作为一项标准程序，应在术后治疗的特定阶段前重复进行全中枢系统成像检查。

MB在诊断时可呈现播散状，有时会发生在脑内，尤其易发生在脑室的蝶鞍下区域。其他成像方法，如核磁共振光谱（MRS）、正电子发射计算机断层扫描（PET）和单光子发射计算机断层扫描（SPECT），等都有助于区分肿瘤复发和治疗后坏死。近期有一项研究报道说可以利用核磁共振成像特征用于区分MB的组织学亚型和分子亚型。classic-MB的表观弥散系数低于anaplastic-MB和large cell-MB的的表观弥散系数。而局部囊肿预示着该MB属于classic-MB或者desmoplastic/nodular-MB。在分子水平上，肿瘤位置和增强模式被认为是指示MB亚型的有力指标。WNT-MB主要位于小脑核和小脑-脑桥角，SHH-MN位于小脑半球，Group3-MB和Group4-MB主要位于第四脑室中线。

## 髓母细胞瘤的分期
分期和随后的风险分级在MB的治疗过程中至关重要。目前的分期分类要求对大脑和整个脊柱进行核磁共振成像，并对脑脊液（CSF）进行分析，因为多达10%的成年人和30%的儿童在发病期时有播散性疾病的证据[@Koeller2003-bq]。分析CSF时首选腰部的CSF，因为它是比脑室液更灵敏的检测播散性疾病的介质。而且应在术后2周从腰部获取CSF，以避免初次切除后出现假阳性。一般根据患者的年龄、残留疾病程度、扩散情况、anaplastic-MB和large cell-MB以及MYC和WNT的状态将患者分为不同的分线等级。术后早期（24-72小时内）核磁共振成像确定的残留疾病在轴向平面上>1.5 平方厘米[@Packer2003-yw]。转移扩展的类型根据 Chang的转移分类确定[@Chang1969-fa]。

60%到70%大于3岁的患者被划分到中风险组。高危患者包括：扩散性患者、手术后残留病灶面积小于1.5平方厘米的患者、MYC表达升高的患者以及属于large cell-MB和anaplastic-MB亚型的患者[@Northcott2012-vx]。

## 髓母细胞瘤的治疗方法
### 手术切除
手术切除是治疗MB的重要手段，通常也是治疗MB的第一选择，理想情况下在初次确诊MB后就应该尽快使用手术全部切除，随后进行一定程度的放疗和化疗。根据肿瘤的位置和大小，在切除前可能需要进行脑室外分流术或第三脑室造口术以降低因卢克夏孔、马耿迪孔或西尔维乌斯导水管处液体循环阻塞而导致的颅内压。约有20%-30%的患者因脑脊液通路瘢痕形成而需要永久性脑室腹腔分流术。MB髓母细胞瘤与第四脑室、有时与脑干关系密切，因此有发病的风险，但儿科神经外科专家经常能够完全切除肿瘤，而不会造成重大的发病。除了感染和机械并发症（如液体渗漏和假性脑膜瘤）外，直接的神经外科操作还可能导致后窝缄默综合征。其特点是在切除术后48-72小时出现缄默症，并伴有严重的小脑功能障碍，如构图障碍、肌张力低下、瘫痪和情绪低落，并有可能持续数月。这可能是继发于网状物质通路的破坏。手术切除的程度最好通过术后脑磁共振成像（术后48小时内）进行评估。然而，肉眼可见的少量肿瘤低于目前扫描仪的分辨率极限可能被遗留下来，因此与神经外科医生仔细讨论并查看手术报告对于制定治疗计划非常重要。通过第二次手术将术后残留肿瘤缩小到小于或等于1.5平方厘米的患者，如果能够及时（通常在第一次手术后两周内）讨论并接受这种方法，则有资格接受标准风险方案。鉴于分子风险类别在分组中的重要作用，不完全切除的相关风险与风险生物学问题存在竞争，如果风险较低，可以接受近乎全切除（near total resection），而不是全切除（gross total resection）。切除的程度与预后有着较强的相关性，比如相较于全部切除（gross total resection），部分切除（subtotal resection）通常预后较差[@Albright1996-ke;@Thompson2016-tn]。如果预后较差的话还可以考虑进行二次手术。不过近期的数据并不支持上述的观点，因此，鉴于MB手术切除后出现小脑缄默症的风险很高，以及高度脆弱结构受损导致无法完全切除时，应避免过度切除覆盖脑干的部分残余肿瘤[@Thompson2016-oy;@Gajjar1996-ij;@Thompson2018-iv;@Schreiber2017-cp]。因此，手术的首要目标和当前目标是获取组织进行组织病理学分析和分子诊断，以及最大限度地安全第消灭肿瘤细胞。事实上，由于分支诊断主要用于确定肿瘤的恶性等级，因此获取组织进行分子诊断对于治疗计划和管理至关重要[@Rutkowski2018-vz;@Mack2017-sy]。

### 放疗
放疗是使用高能射线的电离辐射作用杀死癌细胞来治疗肿瘤的方法，与手术、化疗并列为治疗肿瘤最重要的三种方法。由于MB倾向于在中枢神经系统内部转移，因此目前最成功的放疗效果都是通过照射整个中枢神经系统实现的[@Bloom1982-kc]。对于年龄稍大一些的儿童来说无论使用多大剂量的辐射照射整个中枢神经系统也并不能缓解病情。且照射整个神经系统会带来非常大的负面影响，如永久性的认知功能障碍、神经内分泌紊乱、影响生长发育、不孕不育、畸形以及诱发其他肿瘤发生等。尽管通过降低辐射剂量来避免这个负面结果的努力失败了，但是通过改变给与辐射的方式降低不必要的负面影响。3D质子束放射治疗是另外一种低剂量的治疗方式，因其较高的定向能力使得非靶向组织受到的影响非常小，避免产生其他不利影响[@St_Clair2004-ci]。早期使用质子束治疗MB的结果非常好，且没有显示出明显的毒副作用[@Vatner2018-vf;@Pulsifer2018-rz;@Yock2016-qm]。但是目前还没有直接的比较放疗与质子流治疗肿瘤的研究，因此，在选择具体的治疗方案时还需要考虑其他一些因素，如MB所处的病情等级、肿瘤的大小、有无发生转移、患者的年龄等因素来选择合适的治疗手段。

### 化疗
放疗与化疗的目的非常相似，都是希望使用最低的剂量来达到控制肿瘤生长的最佳效果，同时尽量避免产生其他后遗症。目前治疗MB的化疗药物主要包括：cisplatin、carboplatin、vincristine、cyclophosphamide和lomustine。上个世纪70年代这些化疗药物被用来延长MB患者的生命周期。到90年代时这些药物被用来减缓使用23.4.0Gy/13到36.0Gy/20剂量照射整个中枢神经系统去治疗MB时所产生的后遗症[@Deutsch1996-vn;@Lin2013-rz]。在随后的几年中，这些化疗被证实是手术和放疗的重要辅助手段，并能够显著改善转移性和非转移MB患者的生存率[@Gajjar2006-dg;@Packer2006-xg]。总的来说相较于放疗前给与化疗药物，放疗后给与化疗药物能够显延长患者的生命周期[@Kortmann2000-cn;@Taylor2003-cn]。目前还有联合使用多个化疗药物去治疗MB的，但是这些基本上都是依靠经验联合使用及给药，且没有进行相应的临床实验[@Northcott2019-wy]。

### 细胞免疫治疗
手术切除、放疗和化疗是最早用于治疗MB的方式，但是大约有1/3的患者不能够被治愈，此外经过上述方法治疗后生存下来的患者也常常伴有严重且长期严重的后遗症。细胞免疫治疗是新型的用于治疗肿瘤的手段，是免疫治疗（immunotherapy）的一种，其主要通过改造自身的免疫细胞使其能够识别并杀死肿瘤细胞。且在治疗黑色素瘤、尿道上皮细胞瘤、非小细胞肺癌以及血液瘤等肿瘤上显示出巨大的潜力[@Riley2019-lj;@Chow2019-ev]。

#### 改造T细胞治疗MB
嵌合抗原受体T细胞（chimeric antigen receptor T cell， CAR-T），是指通过改造T细胞受体使其能够识别肿瘤抗原的一种方法。CAR-T在治疗血液瘤方面显示出非常好的效果，如B细胞淋巴瘤和B细胞白血病[@Sterner2021-xk]。但是由于没有肿瘤特异性的抗原，其在治疗固体瘤方面的效果要远不如血液瘤。但是Rivero-Hinojosa等人发现一个多肽（NSSVSGIFTFQK）在高达20% MB患者中存在。目前靶向许多蛋白和多肽的CAR-T基本上都在MB在MB细胞系或者MB异源接种的小鼠身上试验过，其中靶向HER2显示出较好的效果。HER2在MB细胞系Daoy、D283和D425都高表达，此外在MB患者中多大31.1%的患者高表达HER2。早在2007年时研究者使用靶向HER2的CAR-T与Daoy、D283以及MB的原代细胞共培养，发现其能够杀死这些细胞。随后研究者将靶向HER2的CAR-T细胞注射到接种了Daoy细胞的小鼠身上，发现其能够显著地减缓肿瘤的生长。虽然CAR-T治疗能够显著提高小鼠的生存周期，但是治疗后病情会出现反复，且基本上都在治疗后的55天内死亡[@Nellan2018-iv;@Varlet2022-zi;@Ahmed2007-ig]。2010年有一篇文章报道了以为39岁患有肠癌的患者接受了靶向HER2的CAR-T治疗，但是在静脉注射CAR-T的第五天，患者出现了严重的炎症因子风暴（cytokine strom），这是由于肺部的上皮细胞也表达HER2。但是这对于中枢神经系统的肿瘤来说应该不是问题，因为生理状态下大脑组织并不表达HER2[@Morgan2010-kp;@Uhlen2015-ul]。2018年Nellan等人给接种了Daoy的小鼠分别从静脉和瘤内注释靶向HER2的CAR-T，但是从静脉注射的剂量是瘤内注射剂量的5倍，结果都能够是肿瘤消退。同样的治疗效果在接种了D283肿瘤小鼠身上也观察到了。经过治疗的小鼠在安乐死前（治疗后的第37天）的生存率是100%，并且没有小鼠出现复发[@Nellan2018-iv]。由于恒河猴（rhesus macaques）的HER2与人的HER2的相似度非常高（98%），Nellan等人从静脉将靶向HER2的CAR-T注射到恒河猴身上，研究者在恒河猴的脑脊液（Cerebrospinal fluid， CSF）中检测到了靶向HER2的CAR-T，并且观察到脑脊液中IL-2和IL-6水平升高，但是外周血中的IL-2和IL-6并没有升高。说明从静脉注射靶向HER2的CAR-T具有较好的安全性。

在一项临床研究中有三名MB患者分别在第一周、第二周和第三周接受了为期四周的，第一位患者接受了两个疗程的治疗，第二位和第三位患者都接受了三个疗程的治疗，三名患者都没有出现常见的副作用，如头痛、发烧以及超敏C蛋白持续升高等症状。治疗后三名患者都定期接受成像检查，患者1和3的病情次序好转，而患者2的病情表现的比较稳定，但是这个结果还需要更多的临床结果的支持[@Vitanza2021-ic]。

在分析了326个人类Group3-MB后，研究者发现EPHA2、HER2和IL13Ra2在肿瘤组织中的表达水平比正常组织要高。从侧脑室分别注射特异靶向EPHA2和同时靶向EPHA2、HER2以及IL13Ra2的CAR-T显示单针注射就能够显著改善小鼠的生存率，多针注射效果更加明显。在该项研究中研究者还比较了从侧脑室注射和从静脉注射的效果，结果显示从静脉注射的效果要明显好于从侧脑室注射的效果[@]。使用靶向EPHA2的CAR-T和化疗药物Azacytidine联合治疗的研究显示有多大40%的小鼠肿瘤消失同时肿瘤没有复发，而其他的治疗方案最终都出现了肿瘤复发[@Donovan2020-tr]。

除HER2外，其他在MB中表达的基因研究的相对较少。两个独立的研究发现免疫检查点蛋白CD276在96%的MB肿瘤中都表达，共培养特异靶向CD276的CAR-T和MB原代细胞显示能够促进IFN-γ、TNF-a和IL-2的分泌，以及T细胞被激活等。使用接种了Daoy和c-Myc高表达的MB细胞的小鼠的研究发现，静脉注射靶向CD276的CAR-T能够使67%小鼠的肿瘤消退。另外一项研究发现肿瘤细胞CD276的表达水平与生存率之间存在着负相关关系[@Majzner2019-tu;@Li2022-mx]。PRAME是在四种MB亚型中都表达的另外一个抗原，有研究显示其在黑色素瘤中能够激活CD8+ T细胞。靶向PRAME的CAR-T细胞在于Daoy和MB原代细胞共培养是可以抑制肿瘤的生长。此外，给接种了Daoy的小数静脉注射靶向PRAME的CAR-T细胞能够改善荷瘤小鼠的生存率，研究这同时检查小数的一些行为学特征，发现静脉注射靶向PRAME的CAR-T并没有损害小鼠的神经系统[@Epping2006-yj;@Donovan2020-ow;@Orlando2018-mo]。

KLRK1被发现在大多数的肿瘤样本及Daoy和D341 MB细胞系中都表达，在体外共培养Daoy和靶向KLRK1显示，后者能够杀死肿瘤，并且释放TNFa、IFN-γ、IL-10和IL-2等细胞因子。体内的研究显示，靶向KLRK1的CAR-T能够消灭肿瘤，同时没有显示出明显的细胞毒性[@Fernandez2013-gv;@Castriconi2007-nh;@Dai2020-gs]。

鉴于近期CAR-T在细胞及动物水平上取得的进展，多个临床实验已经启动，但是目前所有的临床研究基本都停留在一期临床实验（NCT05131763，NCT04099797，NCT03500991，NCT03638167，NCT04661384）。

#### 改造自然杀伤细胞（nature killer cells）治疗MB
相较于T细胞需要肿瘤特异性的抗原去杀死肿瘤细胞，自然杀伤细胞（nature killer cells，NK cells）杀死肿瘤的机制并不依赖于肿瘤特异抗原。NK细胞的激活依赖于细胞表面两种信号，分别由KLRK1和MHC-I提供。MHC-I是组织相容性抗原I，其几乎在所有的细胞中表达，细胞表面MHC-I水平降低通常意味着该细胞受到病毒感染，细胞表面缺少MHC-I能够激活NK细胞，从而使NK细胞将靶细胞杀死。而KLRK1在靶细胞上表达能够抑制NK细胞的激活。通常细胞表达的KLRK1/MHC-I的比率越高NK细胞越难被激活。体外共培养的研究显示MHC-I/KLRK1的比率与NK细胞激活的程度呈正相关[@Fernandez2013-gv;@Wu2020-zh]。此外，研究显示NK细胞与多种MB细胞系共培养时都能够有效地杀死肿瘤细胞，以及NK细胞在肿瘤组织中浸润的程度与患者的病情有明显的相关性。但是介导NK细胞激活的受体在不同肿瘤细胞中略有差异，且与肿瘤细胞表达的配体存在一定的关联，但是肿瘤细胞表达的肿瘤干细胞标志基因（marker gene）CD133与NK细胞激活程度没有明显关系[@Donovan2020-in;@Castriconi2007-hu;@Perez-Martinez2016-mv;@Liang2021-df]。

TGF-β能够抑制NK细胞激活，而其在MB肿瘤组织中的表达量较高。为了规避这种问题人们将NK细胞表达的TGF-β受体敲除，在NK细胞中敲除TGF-β受体并没有影响到NK细胞分泌细胞因子、杀伤细胞的能力以及细胞增殖的能力。但是遗憾的是目前还没有使用这种NK细胞的基础研究[@Powell2019-fn]。目前有一项使用NK细胞治疗MB的研究，通过向接种了Daoy细胞的小鼠肿瘤内注射NK细胞，与对照相比治疗组肿瘤体积明显变下[@Kennis2019-mc]。

2020年一项使用NK细胞治疗MB的一期临床实验结束，该期实验共有5个MB患者，NK细胞分别从第四脑室或者侧脑室注射，5个病人都没有出现剂量依赖的细胞毒性，但是出现了不同程度的副作用。经过5次治疗，放射成像显示其中一个病人的肿瘤大小减少了约30%。但是治疗后两周该病人出现了癫痫，病情也加重[@Khatua2020-if]。

#### 改造树突状细胞（dendritic cells, DC）治疗MB
树突状细胞是典型的抗原地城细胞，没有杀伤细胞的能力。基于改造DC来治疗肿瘤的模式主要有两种，第一种是使用肿瘤特异抗原在体外刺激DC，然后再将注射患者体内。第二种是在改造的DC帮助下在体外激活并扩增T细胞，然后再把激活的T细胞输入到患者体内[@Schakelaar2023-jm]。尽管MB的突变率相对于其他肿瘤来说相对较低，但是体外共培养显示肿瘤新生抗原（neoantigen）在DC存在下同样可以激活T细胞。体外共培养显示，使用新生抗原激活的T细胞能够有效杀死肿瘤细胞。但是另外一个研究小组发现单独使用新生抗原激活的T细胞并不能杀死肿瘤细胞[@Lasky2022-yp;@Blaeschke2019-of;@Rivero-Hinojosa2021-bv]。Flores等人使用肿瘤总RNA和新生抗原共同处理的DC去激活T细胞，将该T细胞注入到Group3-MB的小鼠身上，发现能够显著提高小鼠的生存周期，此外肿瘤中浸润的激活的T细胞的比例也随着时间稳步提高[@Flores2019-le]。

最近使用DC治疗MB的二期临床试验（NCT013261604）发布了部分实验结果，其显示相较于历史数据，在治疗期间患者的病情没有发生恶化。另外一个DC治疗MB的一期临床实验刚刚结束，其显示使用DC免疫治疗患者没有出现明显的毒副作用（NCT01171469，NCT03615404，NCT00014573）。

#### 改造其他细胞治疗MB
除了改造CD8+ T细胞外，还有通过改造另外两个T细胞亚群NKT细胞和γδT细胞去治疗MB的。NKT细胞主要被脂质激活（通过CD1d受体，而非经典的MHC-II受体），而大脑是人体中脂质含量第二高的器官，所以改造NKT细胞去治疗中枢神经系统肿瘤也受到一定的关注[@Hussain2019-sc]。尽管NKT细胞占所有免疫细胞的比例非常地，但是研究显示能够杀死肿瘤细胞，并激活耗竭得CD8+T细胞和NK细胞[@Bae2019-wj]。一项研究显示大约34.2%的MB肿瘤表达CD1d，Liu等人在体外共培养发现NKT细胞能够杀死CD1d^+^的MB细胞[@Teo2014-mj;@Liu2013-oe]。

γδT细胞是T细胞的一个亚型，主要存在于外周组织，如皮肤、肺以及肠道等[@Diao2020-gh]。有研究显示MB组织中也浸润的有部分γδT细胞，但是不同的研究得到的差异较大。另外，目前也没有改造γδT细胞治疗MB的报道。

## 2-脱氧-D-葡萄糖（2-Deoxy-D-glucose）治疗肿瘤中的机制
### 2-脱氧-D-葡萄糖简介
2-Deoxy-D-glucose（2DG）是一个人工合成的葡萄糖类似物，其2号位置的羟基被氢取代。早在上个世纪50年代2DG就开始被大量的用于科学及临床研究[@Kurtoglu2007-hn;@Zhang2014-rq]。通常认为2DG主要抑制糖酵解过程，但是其对其他的生物代谢过程也有着深远的影响。如剥夺细胞能量（depletion cellular energy）、增加氧化压力（oxidative stress）、干扰N-酰基糖基化过程、诱导自噬以及激活PI3K，MAPK和AMPK等信号通路。通常其所诱导的细胞凋亡是通过多种途径共同起作用的[@Bandugula2013-gn;@Yamaguchi2011-ce;@Kim2013-yk]。

### 2DG诱导肿瘤凋亡的机制
#### 抑制糖酵解
由于2DG能够像天然的葡萄糖一样被葡萄糖转运体摄取到细胞内，所以其能够竞争性地抑制细胞摄取天然葡萄糖。进入细胞后其能够被己糖激酶磷酸化为2-Deoxy-D-glucose-6-phosphate（2DG-6-P），而2DG-6-P不能被磷酸果糖激酶进一步磷酸化成1，6二磷酸果糖，从而导致其在细胞内大量堆积。其在细胞内的堆积能够抑制上游己糖激酶和6-磷酸葡萄糖异构化过程。由于2DG能够抑制糖酵解上游最重要的两个步骤，这导致细胞内ATP减少、抑制细胞分裂，甚至造成细胞凋亡。

细胞内ATP水平的降低会导致AMP/ATP的比率升高，进而激活AMPK信号通路，通过磷酸化下游靶点进而提高了分解代谢的速率[@Kim2013-ut]。另外，细胞内ATP水平的降低会导致细胞对外界诱导凋亡的信号特别敏感，如TNF（tumor necrosis factor）等信号[@Robinson2012-ue;@Wood2008-ze]。p53可以感知细胞内ATP的水平，当细胞内ATP的水平降低时，其能够通过促进氧化磷酸化过程提高细胞内ATP的水平，因而2DG处理也会影响到p53的功能[@Sinthupibulyakit2010-sw]。当激活缺氧诱导因子（Hypoxia-inducible factor，HIF）时，其能够促进葡萄糖转运体以及其他糖酵解通路中的一些酶的表达，因此其能够降低2DG的效果。此外，给与甘露糖（mannose）处理以及过表达Bcl-2都能够减弱2DG诱导凋亡的效果，但是这些处理并不能改善细胞内ATP的水平[@Zagorodna2012-jq;@Raez2013-iz]。

#### 抑制抗氧化过程
细胞内的活性氧（reactive oxygen species，ROS）能够氧化脂肪、氧化蛋白和损伤DNA等，因此其能够干扰氧化还原过程、造成基因组突变和抑制细胞分化等，而这些都是肿瘤的特征[@Scarbrough2012-jv;@Fath2011-ez]。过多的活性氧是对细胞不利的，因此增加细胞内活性氧的产量或者降低细胞内的还原过程都可以杀死肿瘤细胞[@Beneteau2012-by]。葡萄糖代谢速率的增加一方面能够促进戊糖磷酸化途径来增加NADPH的生成，还可以促进丙酮酸的生成，从而减轻细胞的氧化应激以及维持氧化还原的平衡。NADPH 是所有谷胱甘肽和硫氧还蛋白过氧化物酶途径的还原等价物，这两种酶都是主要的细胞硫醇抗氧化剂，负责活性氧和氮物种（ROS 和 RNS）的解毒、维持细胞氧化还原电位以及预防和恢复氧化损伤。丙酮酸对维持细胞内还原型谷胱甘肽水平、抑制超氧化物生成和直接清除过氧化氢至关重要[@Giammarioli2012-ty;@Fernandez-Gomez2006-og]。剥夺细胞的葡萄糖能够促进过氧化物和超氧化物的生成，从而诱导细胞凋亡，2DG模拟的葡萄糖剥夺还会使线粒体产生过氧化物[@Sinthupibulyakit2010-sw]。2DG在细胞内并不能被完全代谢掉，其在代谢过程中只能产生一分子的NADPH，而天然葡萄糖被代谢是能够产生2分子的NADPH，所以2DG处理会使细胞内NADPH和丙酮酸的水平降低，降低了细胞对活性氧的抵抗能力。然而，这种情况可以通过促进p53基因的表达来促进其他抗氧化酶的生成，比如锰超氧化物歧化酶（MnSOD）和谷胱甘肽过氧化酶1（GPx1）[@Sinthupibulyakit2010-sw]。

#### 干扰N酰基糖基化过程
蛋白质的糖基化是一个酶促反应过程，糖基化修饰对于提高蛋白质的稳定性、蛋白质的正确折叠以及细胞的粘附都有非常重要的作用[@]。N酰基糖基化主要是把糖基加到天冬氨酸和精氨酸侧链的氨基上，这个过程通常在内质网的内腔上进行（lumen）。在与蛋白质连接的寡糖组装过程中，甘露糖通过与二磷酸鸟苷（GDP）或多酚磷酸（Dol-P）发生共价反应而转化为甘露糖-GDP。作为蛋白质N-酰基糖基化的前体，甘露糖-GDP在GDP-甘露糖基转移酶的催化下一步步组装到 N-乙酰葡糖胺残基上，形成寡糖链。葡萄糖也参与了这一过程，因为它会转化为G-6-P，后者可通过磷甘露糖异构酶（PMI）进一步转化为6-磷酸甘露糖，然后代谢为甘露糖-GDP，形成蛋白质的寡糖链[@Kurtoglu2007-cs;@Qin2010-xf]。由于2DG的结构与甘露糖相似，所以其也可以干扰N酰基糖基化过程。2DG除了与甘露糖竞争甘露糖-GDP转移酶位点，2DG-GDP在细胞内的形成会导致寡糖连的前提被消耗，进一步破坏了寡糖连的形成[@]。这些异常的寡糖连在细胞内会干扰糖蛋白的形成。虽然细胞内的葡萄糖通过差向异构转变为甘露糖的方式参与到糖基化过程，但是外源的葡萄糖并不能逆转2DG的毒性，因为2DG会阻碍葡萄糖向甘露糖的转化[@Kurtoglu2007-hn]。

抑制糖基化过程会导致蛋白质的折叠异常，异常折叠的蛋白在内质网中大量堆积会激活未折叠蛋白反应（unfold protein response，UPR），严重时会导致内质网功能失调。UPR激活后从两个方面减轻内质网的压力，第一个是抑制蛋白质的翻译过程，从而降低进入内质网的蛋白数量，第二个是其能够促进异常蛋白的降解。但是如果内质网的这种压力持续较长时间，会导致内质网功能受损，同时内质网特异的凋亡因子也会被激活，如C/EBP homologous protein（CHOP），也称为生长阻止和DNA损伤诱导基因153（GADD153）[@Oyadomari2004-za;@Tajiri2006-dh]。敲除CHOP细胞的内质网非常地抗凋亡，其表达量也是检测内质网所受到压力的重要指标[@Zagorodna2012-jq]。研究显示2DG处理能够促进CHOP的表达，说明干扰糖基化过程是2DG诱导细胞凋亡的一种机制[@Boutros2009-qe;@Yu2010-og]。内质网产生压力后也会诱导线粒体凋亡信号，其中就包括激活凋亡前信号蛋白Bcl-2。可以将凋亡前信号蛋白划分成多个亚类，比如Bax、Bak和BH3组，Bim和Puma组。2DG能够非常显著地激活Bax和Bak，说明激活线粒体凋亡通路在在2DG诱导细胞凋亡过程中也起到一定的作用[@Zagorodna2012-jq;@Yamaguchi2011-zt;@Ramirez-Peinado2011-hy]。此外，研究还发现降低Bim和Puma的表达量能够2DG诱导的内质网凋亡的能力[@Zagorodna2012-jq]。许多研究认为，2DG诱导的细胞凋亡是通过干扰糖基化实现的，而非阻断糖酵解过程。因为2DG处理后给与甘露糖能够避免细胞凋亡，但是不能够改变细胞内ATP的水平[@Xi2011-ph;@Zagorodna2012-jq;@Qin2010-it;@Andresen2012-ma]。

#### 诱导自噬
在正常生理状态下自噬（autophagy）是一个非常普遍的分解代谢过程，其参与调控许多生理及病理过程，如肿瘤的发生、神经退化以及衰老等[@Araya2013-ug;@Rangel2022-dg]。细胞自噬是一种细胞死亡方式，不同于细胞凋亡（apoptosis），是由于其凋亡的结构以及凋亡时募集的凋亡因子都与细胞凋亡不同[@Melendez2008-kg]。细胞自噬是细胞抵抗饥饿、缺氧、高温、辐射及荷尔蒙和生长因子剥夺的一种生存方式。在上述压力过程中细胞器以及部分细胞浆被包裹到一个有双层膜构成的自噬体里面，然后自噬体与融媒体融合导致自噬体被降解，讲解的产物为细胞提供物质与能量[@]。除了有循环利用营养物质的功能外，自噬还可以功能受损的细胞器和蛋白质。比如自噬可以通过逐步地降解由过氧化物破坏的线粒体，来避免细胞进入凋亡程序。

自噬一个发生的一个重要标志就是微管结合蛋白LC3发生改变，LC3是一个可溶蛋白，在哺乳动物细胞内分布的非常广泛。在自噬过程中LC3被转移到自噬体里面，然后被磷脂酰乙醇胺修饰，形成LC3-磷脂酰乙醇胺，随后被转移到自噬体膜上[@Giammarioli2012-nw;@Tanida2008-mx]。2D处理能够显著地促进LC3-磷脂酰乙醇胺的形成，说明2DG处理促进了自噬的发生。2DG通过阻遏糖酵解降低细胞内ATP的浓度的方式激活自噬[@Giammarioli2012-ph;@Ben_Sahra2010-yk]。2DG诱导的内质网压力（ER stress）也是可能是诱导自噬发生的方式，因为有研究发现给与甘露糖处理能够减轻2DG诱导的内质网压力，同时终止自噬的发展[@Kurtoglu2007-pt;@Wu2009-tk]。


# 实验材料与方法
## 实验材料
### 主要仪器与设备

|**仪器名称**|**品牌**|**型号**|
|:--|:--|:--|
|恒温水浴锅|Thermo Fisher|Thermo GP 100|
|荧光定量PCR仪|Thermo Fisher|Thermo MiniAmp|
|二氧化碳培养箱|上海宏川实验仪器有限公司|HH.CHP-01|
|紫外分光光度计|||
|台式离心机|Raythan|BC15G|
|-80℃冰箱|||
|-20℃冰箱|Midea|A1068-3101|
|4℃冰箱|Midea|A1068-3101|
|显微镜|NEXCOPE|NIB610|
|全自动化学发光成像仪|广州光仪生物科技有限公司|OI-600|
|小动物活体成像系统|PerkinElmer|IVISLumina III|
|生物安全柜|海尔|HR40-IIA2|
|摇床|Kylin-Bell Lab Instrument|TS-8S|
|冷冻离心机|BIOINSTRU|CR-15|


### 主要试剂与耗材
|**耗材名称**|**品牌**|**货号**|
|:--|:--|:--|
|1.5ml离心管|广州洁特生物过滤股份有限公司|SST001015|
|2.0ml离心管|广州洁特生物过滤股份有限公司|SST001020|
|15.0ml离心管|广州洁特生物过滤股份有限公司|CFT011150|
|50.0ml离心管|广州洁特生物过滤股份有限公司|CFT110500|
|2.0ml细胞冻存管|广州洁特生物过滤股份有限公司|FCT511015|
|6.0cm细胞培养皿|广州洁特生物过滤股份有限公司|TCD000060|
|12孔板|广州洁特生物过滤股份有限公司|TCP011012|
|NC膜|Millipor|782434|
|血球计数板|QIUJING|XB.K.25|
|蛋白marker|碧云天生物科技有限公司|P0061|
|蛋白酶抑制剂|碧云天生物科技有限公司|P1005|
|逆转录试剂盒|||
|CCK8试剂盒|碧云天生物科技有限公司|C0037|
|D-Luciferin|碧云天生物科技有限公司|ST196-25mg|
|太牛血清FBS|Gibco|A5669701|
|DMEM培养基|Gibco|K21111|
|RPMI 1640培养基|Gibco|D211129|
|DMSO|碧云天生物科技有限公司|ST038-100ml|
|0.25% Trypsin EDTA|碧云天生物科技有限公司|C0201-500ml|
|2-Deoxy-D-glucose|碧云天生物科技有限公司|ST1024-250mg	|
|Metformin|碧云天生物科技有限公司|S1741-1g|
|Trizol|碧云天生物科技有限公司|R0016|
|pLKO.1-puro&EGFP|上海逐一生物科技有限公司|NA|

### 小鼠和细胞
|**名称**|**来源**|
|D283|他人赠与|
|D456|他人赠与|
|HEK-293T|中国科学院典型培养物保藏委员会细胞库|
|wild type C56BL/6J|上海南方模式动物科技有限公司|

### 抗体
|**名称**|**供应商**|**货号**|
|:--|:--|:--|


## 实验方法
### 细胞培养
1. 将Group3-MB细胞系从液氮中取出，迅速放到37℃的水浴锅中解冻。
2. 把细胞放到6cm的细胞培养皿中，并加入4ml培养基。
3. 浆细胞放入37℃，5%二氧化碳的细胞培养箱中培养。
4. 每隔两天按1：4比例传代。

培养基配方
- DMEM
- 10% FBS
- 1% 青霉素和链霉素

### 构建MEG3敲降细胞系
- 合成靶向MEG3的片段。
- 将片段退火形成双连，然后连接到pLKO.1-puro&EGFP表达载体上。
- 转化到大肠杆菌中扩增并提取质粒。
- 转染前一天将细胞接种到6孔板，每孔种约25万个细胞。
- 转染前一个小时给细胞换一次液。
- 将表达靶向MEG3小RNA的慢病毒加入到培养基中。
- 两天后向培养基中加入嘌呤霉素筛选，嘌呤霉素的工作浓度为2ug/ml。
- 嘌呤霉素筛选两天后将培养基换成新鲜的无嘌呤霉素的培养基。

### CCK8实验
- 向96孔板中接种细胞，每孔1000个细胞。
- 培养24小时后，丢弃培养基，并用PBS洗一遍细胞。
- 将CCK8试剂按照1：10的比例加入到培养基中，混匀，并向每孔加入100ul含义CCK8的培养基。
- 37℃继续培养45分钟。
- 在酶标仪上读取450纳米吸光度（OD450）。

### Western Blot


### 荧光定量PCR 
- 丢弃培养基，并用PBS洗两次。
- 加入适量的Trizol裂解细胞，并进行适当的吹打。
- 室温放置两分钟。
- 然后按照常规的步骤提取总RNA。
- 总RNA提取后使用立即使用逆转录试剂盒将部分RNA反转录，并保存到-80℃冰箱。
- 使用SYBR染料法进行相对定量。


### 颅内接种肿瘤
- 将Balb/c 裸鼠随机分成两组。
- 给两组小鼠接种D458-luciferase细胞。
- 接种细胞一周后实验组注射2DG（25mM），对照组注射生理盐水。
- 每隔一天注射一次，总共注射三次。
- 并在注射2DG第一周和第四周时使用小动物货梯成像观察肿瘤生长情况。
- 实验结束后将小鼠安乐死，并取肿瘤组织用于测序。


### 细胞克隆形成实验
- 向6孔板中接种细胞，每孔500个细胞。
- 培养箱中培养2周，每隔两天换一次液。
- 两周后使用多聚甲醛固定细胞，并用结晶蓝染色。
- 在显微镜下成像，然后计数。


### RNA-seq数据分析

### 统计分析

# 实验结果
## Group3-MB细胞系对能量应激敏感

## 2DG可以在体内和体外抑制MB的生长

## 2DG通过上调非编码RNA MEG3调控MB的生长

## 2DG调控MEG3下游信号通路影响MB的生长

# 讨论


# 参考文献
::: {#refs}
:::
